version: '3'
services:
  app:
    container_name: graphql-basics
    restart: always
    build: .
    command: sh -c "npm install && npm run dev"
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
