version: '3'
services:
  app:
    container_name: graphql-basics
    restart: always
    build: .
    command: sh -c "npm install && npm run dev"
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/usr/src/app/src
      - ./node_modules:/usr/src/app/node_modules
    env_file:
      - .env
